# Generated by Django 5.1.3 on 2024-12-30 09:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Links",
            new_name="Link",
        ),
    ]
