# Generated by Django 5.1.3 on 2024-12-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_links_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userlinkcategory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
